server:
  port: 8080

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: finwallet-api

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/finwallet}
    username: ${SPRING_DATASOURCE_USERNAME:finwallet}
    password: ${SPRING_DATASOURCE_PASSWORD:finwallet123}

  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

api:
  security:
    jwt:
      secret: ${JWT_SECRET:minhashavesecreta123}
